import { CardanoWASM } from '@hydra-sdk/cardano-wasm'

/**
 * Builds a minting policy script from a public key script.
 *
 * @param pubkeyScript - Public key script object containing type and keyHash
 * Public key script example: { type: 'sig', keyHash: 'abc123...' }
 *
 * Generated by cardano-cli:
 *   ```bash
 *   cardano-cli address key-hash --payment-verification-key-file policy.vkey
 *   ```
 * @returns - Hex-encoded minting policy script
 */
export const buildPolicyScriptFromPubkey = (pubkeyScript: { type: 'sig'; keyHash: string }) => {
	const keyHash = CardanoWASM.Ed25519KeyHash.from_hex(pubkeyScript.keyHash)
	const scriptPubKey = CardanoWASM.ScriptPubkey.new(keyHash)
	const script = CardanoWASM.NativeScript.new_script_pubkey(scriptPubKey)
	return script.as_script_pubkey()?.to_hex() || ''
}

/**
 * Builds a minting policy script from a Bech32 encoded address.
 *
 * @param addressBech32 - Bech32 encoded address
 * @returns - Hex-encoded minting policy script
 */
export const buildMintingPolicyScriptFromAddress = (addressBech32: string) => {
	const addr = CardanoWASM.Address.from_bech32(addressBech32)
	if (!addr.payment_cred()) {
		throw new Error('Invalid address: ' + addressBech32)
	}
	const addrKeyHash = addr.payment_cred()?.to_keyhash()
	if (!addrKeyHash) {
		throw new Error('Error when parsing addrKeyHash')
	}
	return buildMintingPolicyScriptFromKeyHash(addrKeyHash.to_hex())
}

/**
 * Builds a minting policy script from a key hash.
 * @param keyHashHex - Hex-encoded key hash
 * @returns - Hex-encoded minting policy script
 */
export const buildMintingPolicyScriptFromKeyHash = (keyHashHex: string) => {
	const keyHash = CardanoWASM.Ed25519KeyHash.from_hex(keyHashHex)
	const scriptPubKey = CardanoWASM.ScriptPubkey.new(keyHash)
	const script = CardanoWASM.NativeScript.new_script_pubkey(scriptPubKey)
	return script.as_script_pubkey()?.to_hex() || ''
}

/**
 * Extracts the policy ID from a native script.
 *
 * @param script - Hex-encoded native script
 * @returns - Hex-encoded policy ID
 */
export const policyIdFromNativeScript = (script: string) => {
	const nativeScript = CardanoWASM.NativeScript.from_hex(script)
	return nativeScript.hash().to_hex()
}
