services:
  hydra-node-alice:
    image: ghcr.io/cardano-scaling/hydra-node:1.2.0
    volumes:
      - .:/devnet
      - ./persistence/alice:/devnet/persistence/alice
    ports:
      - "4001:4001"
      - "5001:5001"
    command:
      [
        "--node-id", "1",
        "--api-host", "0.0.0.0",
        "--listen", "128.1.2.10:5001",
        "--monitoring-port", "6001",
        "--api-port", "4001",
        "--peer", "128.1.2.30:5003",
        "--hydra-signing-key", "/devnet/credentials/alice/alice-hydra.sk",
        "--hydra-verification-key", "/devnet/credentials/bob/bob-hydra.vk",
        "--persistence-dir", "/devnet/persistence/alice",
        "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000001",
        "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
        "--initial-utxo", "/devnet/initial-utxo.json"
      ]
    networks:
      hydra_net:
        ipv4_address: 128.1.2.10
    restart: always

  hydra-node-bob:
    image: ghcr.io/cardano-scaling/hydra-node:1.2.0
    volumes:
      - .:/devnet
      - ./persistence/bob:/devnet/persistence/bob
    ports:
      - "4003:4003"
      - "5003:5003"
    command:
      [
        "--node-id", "3",
        "--api-host", "0.0.0.0",
        "--listen", "128.1.2.30:5003",
        "--monitoring-port", "6003",
        "--api-port", "4003",
        "--peer", "128.1.2.10:5001",
        "--hydra-signing-key", "/devnet/credentials/bob/bob-hydra.sk",
        "--hydra-verification-key", "/devnet/credentials/alice/alice-hydra.vk",
        "--persistence-dir", "/devnet/persistence/bob",
        "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000001",
        "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
        "--initial-utxo", "/devnet/initial-utxo.json"
      ]
    networks:
      hydra_net:
        ipv4_address: 128.1.2.30
    restart: always


  startup-time-logger:
    image: alpine
    depends_on:
      - hydra-node-alice
      - hydra-node-bob
    command: sh -c "echo $$(( $$(date +%s) * 1000 )) > /shared/startup_time.txt && echo 'Timestamp written:' $$(cat /shared/startup_time.txt)"
    volumes:
      - .:/shared

volumes:
  alice_persistence:
  bob_persistence:

networks:
  hydra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 128.1.2.0/24
          gateway: 128.1.2.1
